# Generated by Django 4.1.7 on 2023-03-06 10:17

import assets.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('brand', models.CharField(max_length=30, null=True)),
                ('purchase_year', models.PositiveIntegerField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='assetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Asset Types',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('newOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newOwnerName', to=settings.AUTH_USER_MODEL)),
                ('oldOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldOwnerName', to=settings.AUTH_USER_MODEL)),
                ('transferredAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.assettype'),
        ),
        migrations.AddField(
            model_name='asset',
            name='currentOwner',
            field=models.ForeignKey(default=assets.models.get_superuser, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
