# Generated by Django 4.1 on 2022-08-30 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('newOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newOwnerName', to=settings.AUTH_USER_MODEL)),
                ('oldOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldOwnerName', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
