# Generated by Django 4.1 on 2022-08-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assettype',
            options={'verbose_name_plural': 'Asset Types'},
        ),
    ]
