# Generated by Django 4.1 on 2022-08-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
