# Generated by Django 4.1 on 2022-08-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transactions',
            new_name='transaction',
        ),
    ]
