# Generated by Django 4.1 on 2022-08-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='brand',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
