# Generated by Django 4.1 on 2022-08-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_asset_brand_alter_asset_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='isActive',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
