# Generated by Django 4.1 on 2022-08-29 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_alter_asset_currentowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='currentOwner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
